

export enum MessageType {
  // COMMANDS
  CARD_POWER_ON_CMD= 0x62,
  CARD_POWER_OFF_CMD= 0x63,
  GET_SLOT_STATUS_CMD= 0x65,
  APDU_COMMAND_CMD= 0x6F,
  ESCAPE_COMMAND_CMD= 0x6B,
  // RESPONSES
  CARD_POWER_ON_RESP = 0x80,
  GET_UIID_RESP= 0x80,
  APDU_COMMAND_RESP= 0x80,
  CARD_POWER_OFF_RESP= 0x81,
  GET_SLOT_STATUS_RESP= 0x81,
  NOTIFY_CARD_STATUS_COMMAND_RESP = 0x50,
  STOP_IDLE_STATUS = 0x50,
  START_IDLE_STATUS= 0x52,
  HARDWARE_ERROR_RESPONSE_RESP= 0x51,
  ESCAPE_COMMAND_RESP= 0x83
}

