apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: civica-card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: civica-card
  template:
    metadata:
      labels:
        app: civica-card
    spec:      
      containers:
      - image: nebulaepyxis/civica-card.backend.civica-card:1.0.16
        name: civica-card
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://civi-card-mongo:27017
        - name: MONGODB_DB_NAME
          value: civica-card
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6mv0ByMprlVOd2tzyw/+BxOylLOTG5+oLFgaCiQu3RSIoVyDXtK9d2+kSmP2qsDE+wqVFEdpw2HrUXB8vhjUpu0CluzIw4m5v6l6ExHqyQHBWTCrX4Aynb3eQIWDm1B5Z592XYBLC+ZMDCDkUeiy7R4rGZnG7BPieAGP7KpO23Yc3YVe16Xkwewp3KOgMwch3uyjLVLu386qAeRfEd6yoMYjt+n5dJ5Lv9ZE+vod+BXOrlbmar3GLnE+x+c07YQfAk1jG2WRucN2wqmBKvygRz/Z50jMEclUjddH2wiXbBp9g83MDSQna93tOxlnhRmCTkzsRZqSRVb7HzjASIbfFQIDAQAB\n-----END PUBLIC KEY-----
        # API - SALES-GATEWAY CONFIG
        - name: SALES-GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: sales-gateway-replies-topic-mbe-civica-card
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        #OTHER CONFIGS
        - name: SAM_CLUSTER_MQTT_CONN_STR
          value: tcp://rcswsyrt:wAQAois_Sqt5@m15.cloudmqtt.com:16858
        - name: READER_MASTER_KEY
          valueFrom:
           secretKeyRef:
             name: civica-card-reload
             key: master_key_reader
        - name: CARD_AUTH_SL1_MAD
          valueFrom:
           secretKeyRef:
             name: civica-card-reload
             key: CARD_AUTH_SL1_MAD
        - name: CARD_AUTH_SL1_ADM
          valueFrom:
           secretKeyRef:
             name: civica-card-reload
             key: CARD_AUTH_SL1_ADM
        - name: CARD_AUTH_SL1_PUBLIC
          valueFrom:
           secretKeyRef:
             name: civica-card-reload
             key: CARD_AUTH_SL1_PUBLIC
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "initial_lock"
        # BACKEND PARAMETERS
        - name: GMT_TO_SERVE
          value: "GMT-5"
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      